# frozen_string_literal: true

require 'net/http'
require 'vpic'

RSpec.describe VPIC do
  describe '.decode_vin' do
    subject(:call) { described_class.decode_vin(vin) }

    let(:vin) { 'test' }
    let(:response_double) do
      instance_double(Net::HTTPResponse,
                      body: File.read(File.expand_path('../fixtures/files/vpic/decode_vin_response.json', __dir__)))
    end

    before { allow(Net::HTTP).to receive(:get_response).and_return(response_double) }

    it 'parses and returns the response json as a hash' do
      expect(call).to eq({ suggested_vin: '',
                           error_code: '0',
                           possible_values: '',
                           additional_error_text: nil,
                           error_text: '0 - VIN decoded clean. Check Digit (9th position) is correct',
                           vehicle_descriptor: '1A8HW582*8F',
                           destination_market: 'U.S., Canada, Mexico',
                           make: 'CHRYSLER',
                           manufacturer_name: 'FCA US LLC',
                           model: 'Aspen',
                           model_year: '2008',
                           plant_city: 'NEWARK',
                           series: 'HG',
                           trim: 'Limited/Signature',
                           vehicle_type: 'MULTIPURPOSE PASSENGER VEHICLE (MPV)',
                           plant_country: 'UNITED STATES (USA)',
                           plant_company_name: 'Newark Assembly',
                           plant_state: 'DELAWARE',
                           trim2: nil,
                           series2: nil,
                           note: nil,
                           base_price: nil,
                           non_land_use: nil,
                           body_class: 'Sport Utility Vehicle (SUV)/Multi-Purpose Vehicle (MPV)',
                           doors: '4',
                           windows: nil,
                           wheel_base_type: nil,
                           track_width_inches: nil,
                           gross_vehicle_weight_rating_from: 'Class 2E: 6,001 - 7,000 lb (2,722 - 3,175 kg)',
                           bed_length_inches: nil,
                           curb_weight_pounds: nil,
                           wheel_base_inches_from: nil,
                           wheel_base_inches_to: nil,
                           gross_combination_weight_rating_from: nil,
                           gross_combination_weight_rating_to: nil,
                           gross_vehicle_weight_rating_to: nil,
                           bed_type: nil,
                           cab_type: nil,
                           trailer_type_connection: 'Not Applicable',
                           trailer_body_type: 'Not Applicable',
                           trailer_length_feet: nil,
                           other_trailer_info: nil,
                           number_of_wheels: nil,
                           wheel_size_front_inches: nil,
                           wheel_size_rear_inches: nil,
                           entertainment_system: nil,
                           steering_location: nil,
                           number_of_seats: nil,
                           number_of_seat_rows: nil,
                           transmission_style: nil,
                           transmission_speeds: nil,
                           drive_type: '4WD/4-Wheel Drive/4x4',
                           axles: nil,
                           axle_configuration: nil,
                           brake_system_type: 'Hydraulic',
                           brake_system_description: nil,
                           other_battery_info: nil,
                           battery_type: nil,
                           number_of_battery_cells_per_module: nil,
                           battery_current_amps_from: nil,
                           battery_voltage_volts_from: nil,
                           battery_energy_k_wh_from: nil,
                           ev_drive_unit: nil,
                           battery_current_amps_to: nil,
                           battery_voltage_volts_to: nil,
                           battery_energy_k_wh_to: nil,
                           number_of_battery_modules_per_pack: nil,
                           number_of_battery_packs_per_vehicle: nil,
                           charger_level: nil,
                           charger_power_k_w: nil,
                           engine_number_of_cylinders: '8',
                           displacement_cc: '5700.0',
                           displacement_ci: '347.83534133997',
                           displacement_l: '5.7',
                           engine_stroke_cycles: nil,
                           engine_model: nil,
                           engine_power_k_w: nil,
                           fuel_type_primary: 'Gasoline',
                           valve_train_design: nil,
                           engine_configuration: 'V-Shaped',
                           fuel_type_secondary: nil,
                           fuel_delivery_fuel_injection_type: nil,
                           engine_brake_hp_from: nil,
                           cooling_type: nil,
                           engine_brake_hp_to: nil,
                           electrification_level: nil,
                           other_engine_info: 'Engine Info: HEMI Multiple Displacement  Sales Code: EZB',
                           turbo: nil,
                           top_speed_mph: nil,
                           engine_manufacturer: nil,
                           pretensioner: nil,
                           seat_belt_type: 'Manual',
                           other_restraint_system_info: nil,
                           curtain_air_bag_locations: nil,
                           seat_cushion_air_bag_locations: nil,
                           front_air_bag_locations: '1st Row (Driver and Passenger)',
                           knee_air_bag_locations: nil,
                           side_air_bag_locations: '1st Row (Driver and Passenger)',
                           anti_lock_braking_system_abs: nil,
                           electronic_stability_control_esc: nil,
                           traction_control: nil,
                           tire_pressure_monitoring_system_tpms_type: nil,
                           active_safety_system_note: nil,
                           auto_reverse_system_for_windows_and_sunroofs: nil,
                           automatic_pedestrian_alerting_sound_for_hybrid_and_ev_only: nil,
                           event_data_recorder_edr: nil,
                           keyless_ignition: nil,
                           sae_automation_level_from: nil,
                           sae_automation_level_to: nil,
                           adaptive_cruise_control_acc: nil,
                           crash_imminent_braking_cib: nil,
                           blind_spot_warning_bsw: nil,
                           forward_collision_warning_fcw: nil,
                           lane_departure_warning_ldw: nil,
                           lane_keeping_assistance_lka: nil,
                           backup_camera: nil,
                           parking_assist: nil,
                           bus_length_feet: nil,
                           bus_floor_configuration_type: 'Not Applicable',
                           bus_type: 'Not Applicable',
                           other_bus_info: nil,
                           custom_motorcycle_type: 'Not Applicable',
                           motorcycle_suspension_type: 'Not Applicable',
                           motorcycle_chassis_type: 'Not Applicable',
                           other_motorcycle_info: nil,
                           dynamic_brake_support_dbs: nil,
                           pedestrian_automatic_emergency_braking_paeb: nil,
                           automatic_crash_notification_acn_advanced_automatic_crash_notification_aacn: nil,
                           daytime_running_light_drl: nil,
                           headlamp_light_source: nil,
                           semiautomatic_headlamp_beam_switching: nil,
                           adaptive_driving_beam_adb: nil,
                           rear_cross_traffic_alert: nil,
                           rear_automatic_emergency_braking: nil,
                           blind_spot_intervention_bsi: nil,
                           lane_centering_assistance: nil })
    end
  end
end
